"""SDS function registry: maps design-spec features to diagram keys and UC ids."""
from __future__ import annotations

# feature name (from build_design_specs SECTIONS) -> diagram file key
FEATURE_KEYS: dict[str, str] = {
    "View Portal Home": "PortalHome",
    "Register": "Register",
    "Login": "Login",
    "Forgot Password": "ForgotPassword",
    "Logout": "Logout",
    "Manage Profile": "ManageProfile",
    "Book Appointment": "BookAppointment",
    "Manage Appointments": "ManageAppointments",
    "View Prescriptions": "ViewPrescriptions",
    "Notifications": "Notifications",
    "Complaints (Patient)": "ComplaintsPatient",
    "Wallet": "Wallet",
    "Insurance": "Insurance",
    "Queue Status": "QueueStatus",
    "Doctor Dashboard": "DoctorDashboard",
    "Consultation & EMR": "ConsultationEMR",
    "Queue Session": "QueueSession",
    "Work Shift Schedule": "WorkShift",
    "Appointment Calendar": "AppointmentCalendar",
    "Patient EMR Timeline": "PatientEMRTimeline",
    "Medical Imaging": "MedicalImaging",
    "Prescription Management": "PrescriptionMgmt",
    "Manage Accounts": "ManageAccounts",
    "Manage Specialties": "ManageSpecialties",
    "Manage Departments": "ManageDepartments",
    "Manage Clinic Rooms": "ManageClinicRooms",
    "Manage Doctors": "ManageDoctors",
    "Manage Patients": "ManagePatients",
    "Admin Dashboard": "AdminDashboard",
    "Manage Pharmacy": "ManagePharmacy",
    "Queue Check-in": "QueueCheckin",
    "Manage Complaints (Staff)": "ManageComplaintsStaff",
    "Staff Dashboard": "StaffDashboard",
}
